os: linux
dist: focal
language: python
edge:
  source: travis-ci/dpl
  branch: update_aws_lambda_am
deploy:
  provider: lambda
  handler_name: test
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  function_name: bsfy_test_function1234
  runtime: nodejs16.x
  role: arn:aws:iam::341288657826:role/bsfy_lambda_role
script:
  - python hello_world.py

